### ISSUE TITLE
bug / cannot pass orders instance to payment simple form in orders.index.html.erb

### ISSUE THREAD

**Issue by debwagon** [wirriamm/aunty-ingredients#15]
**Describe the bug**

**To Reproduce**

**Expected vs actual behavior**

**Screenshots**

**Device**
Is it specific to a device or screen size?

**Additional context**

**Comment by wirriamm** [comment]
See if this is fixed after merging with order-controller branch pull request #18 ?

**Comment by wirriamm** [comment]
@debwagon We can close this?
