### ISSUE TITLE
db / make more listings seed using faker

### ISSUE THREAD

**Issue by debwagon** [wirriamm/aunty-ingredients#16]
**What is it?**
What are the things that need to be migrated or changed

**Why? (be concise and descriptive 🙏)**

**Comment by wirriamm** [comment]
Could consider how specific we want the user to be on what "quantity" of listing entails. Like in g/kg for non-countable items. Should we get them to include it in description or should we have an explicit new field for it in listings?

**Comment by wirriamm** [comment]
Done by Deb at #14
