### ISSUE TITLE
Fix order index view

### ISSUE THREAD

**Issue by jasdang** [wirriamm/aunty-ingredients#27]
**Any more specifics of this user story?**
![image](https://user-images.githubusercontent.com/46719104/83959875-9f650980-a8b4-11ea-81ef-5c34a7c59cbd.png)

**What are the specific to-dos?**

**Any additional context or helpful breadcrumbs? 🍞**

**Comment by wirriamm** [comment]
@jasdang I think this is fixed right? Just wanna confirm with you, if it's okay, can help close the issue

**Comment by jasdang** [comment]
@wirriamm Not yet. Ill do it now
